# Docker-Compose
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://mongo/learn-mean-stack
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - learn-men-stack: /data/db

volumes:
  learn-men-stack: